# Generated by Django 5.2 on 2025-04-03 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='category',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='api.category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='count',
            field=models.PositiveIntegerField(default='0'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='description',
            field=models.TextField(default='dont have'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='is_activated',
            field=models.BooleanField(default='False'),
            preserve_default=False,
        ),
    ]
