# Generated by Django 5.2 on 2025-04-10 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('descriprion', models.TextField(blank=True)),
                ('city', models.CharField()),
                ('address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Internship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('descriprion', models.TextField(max_length=255)),
                ('stipend', models.FloatField()),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Unic', to='api.university')),
            ],
        ),
    ]
